// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/logo.png
var resourceLogoPngData []byte
var resourceLogoPng = &fyne.StaticResource{
	StaticName:    "assets/logo.png",
	StaticContent: resourceLogoPngData,
}

//go:embed assets/icons/compress.svg
var resourceCompressSvgData []byte
var resourceCompressSvg = &fyne.StaticResource{
	StaticName:    "assets/icons/compress.svg",
	StaticContent: resourceCompressSvgData,
}

//go:embed assets/icons/external-link.svg
var resourceExternalLinkSvgData []byte
var resourceExternalLinkSvg = &fyne.StaticResource{
	StaticName:    "assets/icons/external-link.svg",
	StaticContent: resourceExternalLinkSvgData,
}

//go:embed assets/icons/extract.svg
var resourceExtractSvgData []byte
var resourceExtractSvg = &fyne.StaticResource{
	StaticName:    "assets/icons/extract.svg",
	StaticContent: resourceExtractSvgData,
}

//go:embed assets/icons/info.svg
var resourceInfoSvgData []byte
var resourceInfoSvg = &fyne.StaticResource{
	StaticName:    "assets/icons/info.svg",
	StaticContent: resourceInfoSvgData,
}

//go:embed assets/icons/source-code.svg
var resourceSourceCodeSvgData []byte
var resourceSourceCodeSvg = &fyne.StaticResource{
	StaticName:    "assets/icons/source-code.svg",
	StaticContent: resourceSourceCodeSvgData,
}
