# This workflow will build a golang project and deploy the compiled binary to GitHub Pages
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build, deploy and release 7z-GUI-Linux

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write   # Needed for Releases
  pages: write      # To deploy to Pages
  id-token: write   # To verify the deployment originates from an appropriate source
  attestations: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0  # Ensures full history, including tags

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Setup Pages
      uses: actions/configure-pages@v6

    - name: Install Tools
      env:
        GOTOOLCHAIN: auto
      run: |
        sudo apt-get update
        sudo apt-get install -y upx-ucl
        go install github.com/fyne-io/fyne-cross@latest # Use the fyne-cross tool

    - name: Set up Dynamic Folder Names
      run: |
        # Save to GITHUB_ENV so subsequent steps can use these variables
        echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

    - name: Cross-Compile, Optimize, and Compress
      env:
        URL_386: "https://github.com/ip7z/7zip/releases/download/26.01/7z2601-linux-x86.tar.xz"
        URL_AMD64: "https://github.com/ip7z/7zip/releases/download/26.01/7z2601-linux-x64.tar.xz"
        URL_ARM64: "https://github.com/ip7z/7zip/releases/download/26.01/7z2601-linux-arm64.tar.xz"
      run: |
        mkdir -p ./public

        NAME="7z-GUI-Linux"
        
        archs=("amd64" "386" "arm64")

        for arch in "${archs[@]}"; do
          echo "Building for Linux ${arch}"
          
          # Setup Staging Areas
          STAGING_DIR="./staging"
          STAGING_DEBUG_DIR="./debug-staging"
          rm -rf "${STAGING_DIR}" "${STAGING_DEBUG_DIR}"
          mkdir -p "${STAGING_DIR}" "${STAGING_DEBUG_DIR}"

          echo "------------ fyne-cross working... ------------"
          echo "------------   RELEASE BUILD...    ------------"
          fyne-cross linux \
            --arch ${arch} \
            --env GOTOOLCHAIN=auto \
            --icon "cmd/assets/logo.png" \
            --ldflags="-s" \
            --ldflags="-w" \
            --ldflags="-X=main.version=${{ env.GIT_TAG }}" \
            --name "${NAME}" \
            ./cmd
          
          RAW_BINARY_OUTPUT="./fyne-cross/bin/linux-${arch}/${NAME}"
          
          echo "Checking if release binary exists before proceeding"
          if [ ! -f "${RAW_BINARY_OUTPUT}" ]; then
            echo "Error: Release binary for ${arch} not found at ${RAW_BINARY_OUTPUT}"
            exit 1
          fi
          
          # Move release binary to staging
          mv "${RAW_BINARY_OUTPUT}" "${STAGING_DIR}/${NAME}"
          echo "Done: Release binary moved to staging."

          echo "------------   DEBUG build...    ------------"
          fyne-cross linux \
            --arch ${arch} \
            --env GOTOOLCHAIN=auto \
            --icon "cmd/assets/logo.png" \
            --ldflags="-X=main.version=${{ env.GIT_TAG }}" \
            --name "${NAME}-debug" \
            ./cmd
            
          echo "Checking if debug binary exists before proceeding"
          # NOTE: The binary is still named $NAME because --name only changes Fyne's app metadata, not the executable file name
          if [ ! -f "${RAW_BINARY_OUTPUT}" ]; then
            echo "Error: Debug binary for ${arch} not found at ${RAW_BINARY_OUTPUT}"
            exit 1
          fi
          
          # Move debug binary to its staging directory, manually renaming it to have the -debug suffix
          mv "${RAW_BINARY_OUTPUT}" "${STAGING_DEBUG_DIR}/${NAME}-debug"
          echo "Done: Debug binary moved to debug-staging."
          echo "------------ fyne-cross worked hard. ------------"

          echo "Copy supporting files"
          cp ./dist/release/install.sh "${STAGING_DIR}/" || true
          cp ./dist/release/update.sh "${STAGING_DIR}/" || true
          cp ./dist/release/uninstall.sh "${STAGING_DIR}/" || true
          cp ./cmd/assets/logo.png "${STAGING_DIR}/${NAME}.png" || true
          cp ./dist/release/7z-GUI-Linux.desktop "${STAGING_DIR}/" || true
          echo "Done"

          echo "Downloading 7zzs for architecture: ${arch}"
          case $arch in
            "386")
              DL_URL="${URL_386}"
              ;;
            "amd64")
              DL_URL="${URL_AMD64}"
              ;;
            "arm64")
              DL_URL="${URL_ARM64}"
              ;;
          esac

          # Download the archive (-f fails silently on server errors, -L follows redirects)
          curl -f -L "${DL_URL}" -o "downloaded_7z_${arch}.tar.xz"
          
          # Extract it to a temporary directory
          mkdir -p temp_extract
          tar -xf "downloaded_7z_${arch}.tar.xz" -C temp_extract
          
          # Find 7zzs file and copy it to STAGING_DIR (futureproofing with find, in case it's in a nested folder in future)
          find temp_extract -type f -name "7zzs" -exec cp {} "${STAGING_DIR}/" \;
          find temp_extract -type f -iname "license*" -exec cp {} "${STAGING_DIR}/7-zip.license" \;
          
          # Make the binary executable
          chmod +x "${STAGING_DIR}/7zzs"

          # Clean up download files before compression
          rm -rf temp_extract "downloaded_7z_${arch}.tar.xz"
          echo "7zzs added to Staging Area successfully."

          echo "Create Archive"
          TAR_NAME="${NAME}-${arch}-${{ env.GIT_TAG }}.tar.xz"
          echo "Compressing to ${TAR_NAME}..."
          tar -cJf "./public/${TAR_NAME}" -C "${STAGING_DIR}" .
          tar -cJf "./public/debug-build-${TAR_NAME}" -C "${STAGING_DEBUG_DIR}" .
          sha256sum "./public/${TAR_NAME}" > "./public/${TAR_NAME}.sha256"
          sha256sum "./public/debug-build-${TAR_NAME}" > "./public/debug-build-${TAR_NAME}.sha256"
          echo "Done"

          # Cleanup for next iteration
          echo "Cleaning up ${arch} files..."
          rm -rf "${STAGING_DIR}"
          rm -rf "./fyne-cross/bin/linux-${arch}"
          echo "Done"
        done

    - name: Output the files structure into a JSON file
      run: |
        tree -J public > files.json
        cp -r files.json ./public/
        echo "JSON Manifest generated!"

    - name: Make web pages available
      run: |
        # Ensure dist/pages exists, or handle if it doesn't
        if [ -d "./dist/pages" ]; then
          cp -r ./dist/pages/* ./public/
        fi
        echo "Web assets ready!"

    - name: Upload artifact
      # upload artifact in the build stage, so that it is later on accessible in the deploy stage
      uses: actions/upload-pages-artifact@v5
      with:
        # Upload entire repository
        path: './public'

    - name: Create Release
      uses: softprops/action-gh-release@v3
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') # Only run for tags
      with:
        draft: true
        body: >-
          Thank you for using this tool!  
            
          **Installation:**  
          - Download the `.tar.xz` for your architecture below.  
          - Make the `install.sh` script executable (right click -> properties -> permissions -> Make executable).  
          - Double click `install.sh` to install.  
          - You now have 7z-GUI-Linux installed!  
            
          Star this repo if you find this tool useful!  
            
          ---
        generate_release_notes: true
        files: |
          public/*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
